FASTQdownsample:
  memory: 4G
__default__:
  memory: 1G
bamCoverage:
  memory: 5G
bamCoverage_RPKM:
  memory: 5G
bamCoverage_coverage:
  memory: 5G
bamCoverage_raw:
  memory: 5G
bamCoverage_unique_mappings:
  memory: 5G
bowtie2Index:
  memory: 10G
bwaIndex:
  memory: 8G
bwamethIndex:
  memory: 20G
createGenomeFasta:
  memory: 20G
create_snpgenome:
  memory: 30G
downloadGTF:
  memory: 20G
fastaDict:
  memory: 4G
filter_reads_umi:
  memory: 10G
hisat2Index:
  memory: 2G
make2bit:
  memory: 8G
plotCorrelation_pearson:
  memory: 3G
plotCorrelation_pearson_allelic:
  memory: 5G
plotCorrelation_spearman:
  memory: 3G
plotCorrelation_spearman_allelic:
  memory: 2G
plotCoverage:
  memory: 1G
plotEnrichment:
  memory: 1G
plotFingerprint:
  memory: 1G
plotPCA:
  memory: 4G
plotPCA_allelic:
  memory: 4G
plot_heatmap_CSAW_up:
  memory: 10G
snakePipes_cluster_logDir: cluster_logs
snakemake_cluster_cmd: module load slurm; sbatch --ntasks-per-node 1 -p bioinfo --mem-per-cpu
  {cluster.memory} -c {threads} -e cluster_logs/{rule}.%j.err -o cluster_logs/{rule}.%j.out
  -J {rule}.snakemake
snakemake_latency_wait: 300
snp_split:
  memory: 10G
starIndex:
  memory: 8G
