baseDir: /package/anaconda3/envs/snakePipes-2.4.2/lib/python3.9/site-packages/snakePipes
blacklist: null
clusterConfig: shared/cluster.yaml
clusterConfigFile: null
configFile: null
configMode: manual
createDAG: false
effectiveGenomeSize: null
emailAddress: null
emailSender: null
genome: GRCm38_gencode_release19
genomeURL: /data/processing2/sikora/genome.fa
gtfURL: /data/processing2/sikora/genes.gtf
ignoreForNormalization: null
keepTemp: false
local: false
maxJobs: 5
oldConfig: null
onlySSL: false
organismsDir: shared/organisms
outdir: /data/processing2/sikora/GRCm38_gencode_release19
pipeline: createIndices
rmskURL: null
rmsk_file: null
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /package/anaconda3/envs   --use-conda
  --conda-prefix /localenv/sikora/snakePipes_envs '
spikeinBlacklist: null
spikeinExt: _spikein
spikeinGenomeURL: null
spikeinGtfURL: null
tempDir: /data/extended/
tools: all
toolsVersion: true
userYAML: true
verbose: false
workingdir: /data/processing2/sikora/GRCm38_gencode_release19
